#!/usr/bin/env bash

function xval() {
	xrdb -query | grep "$1" | head -1 | cut -f 2
}

theme_name="$(readlink ~/.config/xthemes/themes/default | xargs basename)"
template_dir="$HOME/.config/xthemes/templates"

# $1 = template name
# $2 = destination
# $3 = comment prefix
function make_config() {
	rm "$2"
	if [ -n "$3" ]; then
		echo -e "$3 This file is autogenerated. Please edit $template_dir/$1 instead.\n" > "$2"
	fi
	cat "$template_dir/$1" >> "$2"
}

# rofi

rofi_config="$HOME/.config/rofi/variables.rasi"
make_config "rofi.rasi" "$rofi_config" "//"

sed -i -E \
	-e "s/^(\s*)v-font: .+;\$/\1v-font: "\""$(xval rofi.font)"\"";/" \
	-e "s/^(\s*)v-accent-color: .+;\$/\1v-accent-color: $(xval rofi.accentColor);/" \
	-e "s/^(\s*)v-bg-color: .+;\$/\1v-bg-color: $(xval rofi.bgColor);/" \
	-e "s/^(\s*)v-fg-color: .+;\$/\1v-fg-color: $(xval rofi.fgColor);/" \
	-e "s/^(\s*)v-selection-bg-color: .+;\$/\1v-selection-bg-color: $(xval rofi.selectionBgColor);/" \
	-e "s/^(\s*)v-selection-fg-color: .+;\$/\1v-selection-fg-color: $(xval rofi.selectionFgColor);/" \
	"$rofi_config"

# xsettingsd

mkdir -p ~/.config/xsettingsd

xsettingsd_config="$HOME/.config/xsettingsd/xsettingsd.conf"
make_config "xsettingsd.conf" "$xsettingsd_config" "#"

sed -i \
	-e "s|Net/ThemeName.*|Net/ThemeName \"$(xval gtk.theme)\"|" \
	"$xsettingsd_config"

# gtk

gtk_config="$HOME/.config/gtk-3.0/settings.ini"
make_config "gtk.ini" "$gtk_config" "#"

sed -i \
	-e "s/gtk-theme-name = .*/gtk-theme-name = $(xval gtk.theme)/" \
	"$gtk_config"

# picom

picom_config="$HOME/.config/picom/picom.conf"
make_config "picom.conf" "$picom_config" "#"

sed -i -E \
	-e "s/^shadow = .+;\$/shadow = $(xval picom.shadow);/" \
	-e "s/^shadow-radius = .+;\$/shadow-radius = $(xval picom.shadowRadius);/" \
	-e "s/^shadow-offset-x = .+;\$/shadow-offset-x = $(xval picom.shadowOffsetX);/" \
	-e "s/^shadow-offset-y = .+;\$/shadow-offset-y = $(xval picom.shadowOffsetY);/" \
	-e "s/^shadow-opacity = .+;\$/shadow-opacity = $(xval picom.shadowOpacity);/" \
	"$picom_config"

# dunst

# If I wanted to define separate values for low, normal, and critical notifications, I could add a comment in dunstrc to indicate which line to target

dunst_config="$HOME/.config/dunst/dunstrc"
make_config "dunstrc" "$dunst_config" "#"

sed -i -E \
	-e "s/background = .+/background = \"$(xval dunst.background)\"/" \
	-e "s/foreground = .+/foreground = \"$(xval dunst.foreground)\"/" \
	"$dunst_config"

# eww

eww_config="/home/addison/.config/eww/xresources.scss"
make_config "eww.scss" "$eww_config" "//"

# TODO: I don't like this... Wish I could grab these from in the thing... (I guess the color defs aren't needed, just colors for specific elements...)
sed -i -E \
	-e "s/bg: #.+;/bg: $(xval eww.bg);/" \
	-e "s/fg: #.+;/fg: $(xval eww.fg);/" \
	-e "s/focusedDesktopBg: #.+;/focusedDesktopBg: $(xval eww.focusedDesktopBg);/" \
	-e "s/focusedDesktopFg: #.+;/focusedDesktopFg: $(xval eww.focusedDesktopFg);/" \
	-e "s/font-family: .+;/font-family: $(xval eww.fontFamily);/" \
	-e "s/font-size: .+;/font-size: $(xval eww.fontSize);/" \
	\
	-e "s/black: #.+;/black: $(xval st.color0);/" \
	-e "s/red: #.+;/red: $(xval st.color1);/" \
	-e "s/green: #.+;/green: $(xval st.color2);/" \
	-e "s/yellow: #.+;/yellow: $(xval st.color3);/" \
	-e "s/blue: #.+;/blue: $(xval st.color4);/" \
	-e "s/magenta: #.+;/magenta: $(xval st.color5);/" \
	-e "s/cyan: #.+;/cyan: $(xval st.color6);/" \
	-e "s/white: #.+;/white: $(xval st.color7);/" \
	\
	-e "s/b-black: #.+;/b-black: $(xval st.color8);/" \
	-e "s/b-red: #.+;/b-red: $(xval st.color9);/" \
	-e "s/b-green: #.+;/b-green: $(xval st.color10);/" \
	-e "s/b-yellow: #.+;/b-yellow: $(xval st.color11);/" \
	-e "s/b-blue: #.+;/b-blue: $(xval st.color12);/" \
	-e "s/b-magenta: #.+;/b-magenta: $(xval st.color13);/" \
	-e "s/b-cyan: #.+;/b-cyan: $(xval st.color14);/" \
	-e "s/b-white: #.+;/b-white: $(xval st.color15);/" \
	"$eww_config"
