#!/usr/bin/env bash

# TODO:
# - no border when only one window tiled
# - anything else???

# key reference: https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h

# TODO: can I still use Super+Enter in Chrome?

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# Remove all existing keybindings
hc keyunbind --all

# Mod key = Super key
Mod=Mod4

# Custom actions
hc keybind $Mod-p spawn rofi -show drun -show-icons -i

# Misc crap
# hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-w close
hc keybind $Mod-Shift-Return spawn "${TERMINAL:-xterm}"

# Frame/[...] manipulation
# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

hc keybind $Mod-minus       split   bottom  0.5
hc keybind $Mod-backslash   split   right   0.5

# TODO: what's this???
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
# TODO: what's this???
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-t pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace    cycle_monitor
hc keybind $Mod-Tab          cycle_all +1
hc keybind $Mod-Shift-Tab    cycle_all -1
hc keybind $Mod-bracketleft  cycle -1
hc keybind $Mod-bracketright cycle 1
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_border_width 2
# `frame_border_width` is `0` so these don't matter
hc set frame_border_active_color '#BBBBBB'
hc set frame_border_normal_color '#33415E'

# Don't show borders for empty frames unless focused
hc set always_show_frame off
# `frame_bg_transparent` is `off` so these don't matter
# hc set frame_bg_normal_color '#FF000'
# hc set frame_bg_active_color '#FF000'

# Don't show background colors for frames
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 4

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings on
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# hc attr theme.active.color '#BBBBBB'

hc attr theme.inner_width 0
hc attr theme.border_width 2
hc attr theme.color '#33415E'
hc attr theme.active.color '#BBBBBB'
# hc attr theme.outer_color '#FF0000'

# hc attr theme.floating.border_width 2
# hc attr theme.floating.outer_width 0
# hc attr theme.floating.outer_color black
# hc attr theme.active.outer_color '#3E4A00'
# hc attr theme.background_color '#141414'

# TODO: Do I want this??? Maybe??? Maybe not???
# Prob not but maybe add a way to toggle it?
hc set hide_covered_windows off

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done
