#!/usr/bin/zsh

MONITOR=$(xrandr --listmonitors | grep '*' | awk '{print $4}')

function xval() {
	xrdb -query | grep "$1" | cut -f 2
}

_NET_WM_STRUT_PARTIAL=1

killall sxhkd; sxhkd &

bspc monitor "$MONITOR" -d 1 2 3 4 5 6

bspc desktop 1 -l monocle
bspc desktop 2 -l tiled

bspc rule -r "*"

bspc config border_width "$(xval bspwm.borderSize)"
bspc config window_gap "$(xval bspwm.gap)"

bspc config active_border_color "$(xval bspwm.normalBorder)"
bspc config normal_border_color "$(xval bspwm.normalBorder)"
bspc config focused_border_color "$(xval bspwm.focusedBorder)"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      "$(xval bspwm.gaplessMonocle)"
bspc config focus_follows_pointer true

bspc config single_monocle true

# TODO: use the focused monitor rather than the primary monitor
ssize=$(xrandr | fgrep '*' | head -1 | awk '{print $1}')
swidth=$(echo $ssize | cut -d "x" -f 1)
sheight=$(echo $ssize | cut -d "x" -f 2)

posx=$((swidth / 6))
posy=$((sheight / 6))
sizex=$(($posx * 4))
sizey=$(($posy * 4))

bspc rule -a Project-slippi state=fullscreen
bspc rule -a Ranger state=floating rectangle="${sizex}x${sizey}+${posx}+${posy}"
bspc rule -a Sxiv state=fullscreen
bspc rule -a Gpick state=floating
bspc rule -a Gimp state=floating follow=on
bspc rule -a steam follow=no

# Don't let windows steal focus, could be useful...
# bspc config ignore_ewmh_focus true

# Get rid of the gap on all monitors except the main one
# xrandr --listmonitors | sed 1,1d | awk '{ print $4 }' | xargs -L1 -I '{}' bspc config -m {} top_padding 0

polybar_bar_name="$(xval polybar.bar)"
for m in $(xrandr --listmonitors | grep '+' | awk '{print $4}'); do
	bspc config -m "$m" top_padding "$(xprop -name "polybar-${polybar_bar_name}_${m}" _NET_WM_STRUT | awk -e '{ print $5 }' | cut -d ',' -f 1)"
done

# bspc config -m "$MONITOR" top_padding "$(xprop -name "polybar-${polybar_bar_name}_${MONITOR}" _NET_WM_STRUT | awk -e '{ print $5 }' | cut -d ',' -f 1)"

# Hmmmm...
# polybar-msg cmd hide
# polybar-msg cmd show
